### ISSUE TITLE
Praise and few comments

### ISSUE THREAD

**Issue by astrand** [magnetikonline/rsyncbackuprotation#1]
First of all: this software is great! I've used various backup solutions over the years and this is really one of the best! Then, a few comments:

- It would be nice if the actual script (rsyncd-rotation.sh) did not contain any configuration, so that it could be installed machine wide, even though you might want to have different backup areas with different REVISION_COUNT. Perhaps this could be solved by letting the script read REVISION_COUNT from a file in $RSYNC_MODULE_PATH?

- Also, I think you should drop the ".sh" suffix from the script. Looks better in /usr/bin, and no need to change stuff if you re-implement in another language.

- I can report that rsyncbackuprotation works great from Windows as well, in conjunction with https://itefix.net/cwrsync. 

- Is it possible to use relative paths in ~/rsyncd.conf? Typically, my files looks like:

    ```
    list = false
    log file = /home/user/rsyncdefault.log
    log format = %i %f [%l]
    read only = false
    transfer logging = true
    use chroot = false

    [foo-nightly]
    log file = /home/user/foo-nightly/00default.log
    path = /home/user/foo-nightly
    post-xfer exec = /home/user/foo-nightly/rsyncd-rotation.sh
    ```

    Ie /home/user/foo-nightly is repeated two times. Is it possible to use relative paths for "log file" and/or "post-xfer exec"?

**Comment by magnetikonline** [comment]
Hello @astrand 
Firstly, thanks for the kind words about the script - great to hear you have found it of use! I'm still using it everywhere myself - find it's simply the best way to do incremental backups - hard links just make it trivially simple and save tonnes of disk.

Note, I did slightly edit your question for more MarkDown (easier to read!). 

To answer your points:

- Love it, yeah `REVISION_COUNT` really should be set outside of the script. What I will do (and I _assume_ it works) is to be able to pass an optional argument to `post-xfer exec =` to control retention, which would be heaps better.
- Maybe I could drop the suffix, but to be honest I doubt I would need to ever re-implement in another lang (like Python) - I like to stretch the bounds of Bash anyway :smile: - I guess you can always symlink it to another name.
- Nice that it works on Windows! I'll add that to the `README.md` - but I have to wonder, how does cwrsync (and I'm guessing cygwin) handle hard links with NTFS? Does it even work?
- Relative paths there yes/no workie would be down to Rsync itself, it might - I guess you would have to test it?

Thanks again - I'll try to get to your suggestions when time allows.

**Comment by astrand** [comment]
Thanks for the comments. Wrt Windows support, I mean that the "client side" works on Windows. I backup my Windows 7 machines to my Linux server, which runs CentOS. Thus, no need for hard links in NTFS.

**Comment by magnetikonline** [comment]
No dramas @astrand - again, appreciate all your feedback.

I'm certainly going to implement your first suggestion - remove the need to hack rotation count in the script itself - making it generic for reuse across a single system. Nice find. :+1: 
 
Also, on your point of "repeated use of `foo-nightly` in your example above - I just noted from the rsync.conf [man page](https://www.samba.org/ftp/rsync/rsyncd.conf.html) that `path =` can take environment variables (including ones that Rsync sets on connect!) - so you might be able to (depending on your module setup) do something like this with a single `path =` definition only in your `rsync.conf` at the receiving side globally, and avoid having to define it per module:

```sh
path = /home/%RSYNC_USER_NAME%

# or....

path = /home/%RSYNC_MODULE_NAME%
```

This _might_ also work for `log file =` and `post-xfer exec =` - man page doesn't say so, but you might be lucky!

**Comment by magnetikonline** [comment]
Hey @astrand - just quickly, I have been doing some updates recently (as you might have seen).

I have a few more things you might be interested in - which somewhat cover above. I'll ping you when ready. 😄

**Comment by magnetikonline** [comment]
Okay @astrand - pushed some updates - two new arguments can be passed.

https://github.com/magnetikonline/rsyncbackuprotation#optional-arguments

The `-l` option allows logging to file, and (what you wanted) a `-r` option now lets you set a rotation count per module - meaning no hacking of the script itself.
